# Generated by Django 2.2.5 on 2019-12-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(default='default.jpg', upload_to='img_estaciones')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
