# Generated by Django 2.2.5 on 2019-12-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='genero',
            field=models.CharField(default='No definido', max_length=20),
        ),
        migrations.AddField(
            model_name='juego',
            name='multijugador',
            field=models.BooleanField(default=False),
        ),
    ]
